### ISSUE TITLE
Error in [: incorrect number of dimensions

### ISSUE THREAD

**Issue by fgarciacnio** [mathiaskalxdorf/IceR#8] opened 2021-09-08 10:47 UTC
I tried to Run iceR in windows with two thermo .raw. The process seems to work fine until saving quantification results after alignement scoring and filter.
 Then, the programs stops with a warning.
 1] "20210829_QC02_HEK_01 - FDR of peak selection: 0.6 %"
[1] "20210830_QC02_HEK_01 - FDR of peak selection: 0.6 %"
[1] "Save quantification results after alignment scoring"
[1] "Removed 692 isotope features (3.1 %) as they dont show significant ion accumulation in any sample."
[1] "Removed 120 (72 isotope) features from quantification results due to too high variability in alignment between samples."
[1] "20210829_QC02_HEK_01: Removed 0 (0 isotope) quantifications (0 %) due to uncertain peak selection"
[1] "20210830_QC02_HEK_01: Removed 0 (0 isotope) quantifications (0 %) due to uncertain peak selection"
[1] "20210829_QC02_HEK_01: Removed 1988 isotope quantifications (3.9 %) due to discrepancy in peak selection between mono-/+1-isotope features"
[1] "20210830_QC02_HEK_01: Removed 1920 isotope quantifications (3.7 %) due to discrepancy in peak selection between mono-/+1-isotope features"
[1] "Quantification without imputation: 5.9 % missing values"
[1] "Quantification with imputation: 3.8 % missing values"
[1] "Save quantification results after alignment scoring and filter"
Warning: Error in [: incorrect number of dimensions
  2: shiny::runApp
  1: runIceR
Some advise?
Thanks in advance

**Comment by mathiaskalxdorf** [comment] 2021-09-08 11:55
Hey, that looks like an error which should not happen. If I see it correctly, then you are using here IceR for 2 samples, right? As the error is difficult to spot in the code without more details, would it be possible for you to upload the two raw files + your MaxQuant txt-folder somewhere so that I can try to reproduce this error on my side? This would allow me to spot the error and hopefully fix it soon.
Thanks a lot and best regards,
Mathias

**Comment by fgarciacnio** [comment] 2021-09-08 12:01
Hi Matthias.
Thank you very much for your help.
Both files are our QC standard (1 ug HEK extract) run in a QExactive-HF
I can upload the zipped maxquant output and the two raw files via wetransfer. If you are not able to access to them ,I can also upload them to our institutional onedrive as you prefer.
Best regards
Fernando

**Comment by mathiaskalxdorf** [comment] 2021-09-08 12:12
Both should be fine, although I never used wetransfer yet. Maybe it works easiest via a onedrive link.

**Comment by fgarciacnio** [comment] 2021-09-08 12:14
Done! Let me know if you can access to the files.
Fernando

**Comment by mathiaskalxdorf** [comment] 2021-09-08 12:28
I can´t see a link to the files here in your message(s). Did you add one to your last message?

**Comment by fgarciacnio** [comment] 2021-09-08 12:30
I think you have to click the link and then, download both files.
Fernando

**Comment by mathiaskalxdorf** [comment] 2021-09-08 12:45
Sorry, again. I can **not** see a link here to the files in your last messages. Can you add the link to your next response please? If such a link is maybe automatically removed by github while sending a post, we should maybe message via email. But let´s see. Please just try again to put the link in your next message. Thanks again.

**Comment by fgarciacnio** [comment] 2021-09-08 13:28
https://fundacioncnio-my.sharepoint.com/:f:/g/personal/fgarcia_cnio_es/EgVqu7cSEmNJrxovG1l7w9sBTNYC00O1gKvS52pJSBaUdg?e=5%3aGMIQuN&at=9
________________________________

**Comment by mathiaskalxdorf** [comment] 2021-09-09 06:31
Hi Fernando, 

I had a look into your data and could spot the issue. At the end of the IceR run, as a QC it compares the observed new quantifications with what MaxQ observed per peptide and per sample. For that purpose it loads the peptides.txt file and expects individual intensity columns per sample (typically column names are "Intensity sample1" and "Intensity sample2" and so on). In your case it looks like there is only one Intensity column in the peptides.txt file. There are now two possible reasons I can see for that: 1.) Something changed with the newest MaxQ version (I see that you used Version 2.0.2.0 but we tested IceR yet only until 1.6.14) or more likely 2.) both QC samples were defined to be somehow merged together by MaxQ which would also explain why there is only a single Intensity column in peptides.txt and proteinGroups.txt. Can you check your MaxQ settings that both samples are not somehow merged or treated as fractions or something like that? For the future I included now for the next release a check up-front of the IceR run which tests if all required columns and intensities for at least 2 samples are present. Otherwise it will return an error.

Best,

Mathias

**Comment by fgarciacnio** [comment] 2021-09-09 06:40
Hi Matthias.
I think you are right. MaxQuant did not split the peptide intensities because I didn´t selected LFQ option (we check or QC for PSMs, peptides and proteins without further analysis). I going to re-run MaxQuant with the LFQ enable and repeat IceR. Do you recommend to use MBR option prior to IceR?
Thanks a lot and I will keep you informed if it works with the LFQ on.
Best regards
Fernando

**Comment by mathiaskalxdorf** [comment] 2021-09-09 07:12
We typically have MBR switched on as we afterwards want to compare both results (and it is only fair if MBR is switched on for MaxQ) and my recommendation would be to always have MBR switched on for subsequent IceR analysis. Nonetheless, IceR would also work if MBR is switched off.

**Closed as completed** 2021-09-13 06:06 UTC
